### yml 파일 예시입니다. 각자 변경해서 사용해주세요.❗️여기는 절대 개인정보 입력 ❌ ###

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newsfeed_db
    username: your_mysql_username
    password: your_mysql_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
